image: maven:latest

dependencies:
    - repository: tof/plugins/raidcraft/raidcraft-api
    on: master
    - repository: tof/plugins/raidcraft/rcitems
    on: master
    - repository: tof/plugins/raidcraft/combatbar
    on: master

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
  artifacts:
    name: Plugin
    paths:
    - target/*.jar
    expire_in: 1 week